### ISSUE TITLE
[2주차 - 1] ATM

### ISSUE THREAD

**Issue by Jewan1120** [T4F1/Algorithm#17]
## 문제 
- 문제 사이트: 백준
- 문제 이름: [ATM](https://www.acmicpc.net/problem/11399)
- 문제 번호: 11399

### 문제 풀이 템플릿
```
### 시간복잡도 생각해보기
- 

### 풀이 아이디어
- 

### 의사코드 / 풀이 과정
- 

```

**Comment by yeo-li** [comment]
### 시간복잡도 생각해보기
- N은 1 ≤ N ≤ 1,000 이고, P는 1 ≤ Pi ≤ 1,000 이기 때문에, 최대 시간 복잡도는 `O(NlogN)` 이다.

### 풀이 아이디어
- P값을 입력 받은 뒤, 배열에 저장
- `Arrays.sort()`를 이용하여 정렬함. 이때 시간 복잡도는 `O(NlogN)`이므로 위의 최대 시간 복잡도를 만족함.
- 정렬된 값에 `p[i] * (N - i)`를 해주어 최종 결과값을 저장

### 의사코드 / 풀이 과정
```
- N: 정수
- result: 정수
- P: 정수 배열

N ← input()
for i range(0, N - 1)
  P[i] ← input()

P.sort() // O(nlogn)

result ← 0
for i range(0, N - 1)
   result += P[i] * (N - i)

print(result)
```

**Comment by chaerish** [comment]
### 시간복잡도 생각해보기
- N을 받아 배열에 넣음-> O(N)
- 배열을 정렬함 ->  O(NlogN), Arrays.sort()는 Dual-Pivot QuickSort을 사용해 시간 복잡도가 O(NlogN)이다.
- 각 합을 구함 -> O(N)
- 따라서 O(N) + O(NlogN)  => `O(NlogN)`

### 풀이 아이디어
- 가장 작은 시간을 먼저 처리하면 대기시간이 적게 걸리므로,
- 처음 배열을 받은 뒤 오름차순으로 정렬해주면 된다.
- 또, 배열을 돌면서 오름차순으로 정렬한 배열들을 그 전 배열에 더해 대기시간을 게산한다.
### 의사코드 / 풀이 과정
```
Arrays.sort(arr);
for(int i = 1; i<arr.length; i++){
 arr[i]+= arr[i-1];
}
for(int i = 1; i<arr.length; i++){
 answer+= arr[i];
}
print(answer)
```

**Comment by rladmstn** [comment]
### 시간복잡도 생각해보기
- 1 ≤ N ≤ 1,000
- PriorityQueue의 삽입 : `O(logN)`
- PriorityQueue의 삭제 : `O(logN)`
- N개 요소에 대해 수행하므로 `O(NlogN)+O(NlogN)`
- 최종 : `O(NlogN)`

### 풀이 아이디어
- 입력 받을 때 우선순위 큐에 삽입하면 자동으로 오름차순 정렬되는 성질 사용
- 가장 적게 걸리는 시간 -> 가장 많이 반복되면 시간 합의 최솟값 구하기 됨

### 의사코드 / 풀이 과정
```java
PriorityQueue<Integer> pq = new PriorityQueue<>();
int sum = 0; // 최종 시간 합

for(N만큼)
      pq.add(입력);

for(int i=0; i<n; i++)
      sum += pq.poll() * (n-i);
```

**Comment by Jewan1120** [comment]
### 시간복잡도 생각해보기
- 1 ≤ N ≤ 1,000 &rarr; 10^3이므로 O(N^3)까지 가능
- 정렬 후 선형 탐색 가능

### 풀이 아이디어
- 그리디한 방식으로 진행하기 위해 적은 시간이 걸리는 사람을 앞으로 정렬하여 차례대로 돈 인출
- 앞에서부터 `걸리는 시간 * 남은 인원`을 모두 더해주면 됨
### 의사코드 / 풀이 과정
```java
def main() 
  int[] arr // 걸리는 시간들
  int total // 총 시간
  Arrays.sort(arr) // 배열 정렬
  for(i = 0 < n)
    total += arr[i] * (n - i) 
  total 출력

```
