### ISSUE TITLE
[2주차 - 4] 센서

### ISSUE THREAD

**Issue by Jewan1120** [T4F1/Algorithm#20]
## 문제 
- 문제 사이트: 백준
- 문제 이름: [센서](https://www.acmicpc.net/problem/2212)
- 문제 번호: 2212

### 문제 풀이 템플릿
```
### 시간복잡도 생각해보기
- 

### 풀이 아이디어
- 

### 의사코드 / 풀이 과정
- 

```

**Comment by Jewan1120** [comment]
### 시간복잡도 생각해보기
- 1 ≤ N ≤ 10,000
- 1 ≤ K ≤ 1,000 
- N x K = 10^7이므로 O(N x K) 가능

### 풀이 아이디어
- `K개의 집중국`을 세우는데 `수신 가능 영역의 길이의 합을 최소화` &rarr; 그리디한 방식으로 선택
  - 전체 배열을 K개로 나눠주는 과정이 필요
- 입력으로 주어지는 좌표가 정렬이 되어있지 않으므로 정렬
- `int[] diff`: 각 요소들의 차이로 새로운 배열을 만듦 
- 해당 배열에서 길이가 큰 것들은 이어지는 것보다 자르는 것이 더 최적 &rarr; `그리디`
- `diff` 배열을 내림차 순으로 정렬
- 잘라야하는 `diff` 요소를 `K - 1`개 남기고 전부 합 &rarr; `수신 가능 영역의 길이의 합의 최소`

### 의사코드 / 풀이 과정
```java
def main() 
...
int[] diff = new int[n - 1]; // 인접한 요소의 차이
for (int i = 0; i < n - 1; i++)
  diff[i] = arr[i + 1] - arr[i];
Arrays.sort(diff);
int result = 0, len = diff.length;

// 기존 arr 배열을 K개로 쪼개기..
// diff[i]를 더하는 것이 집중국을 세우는 것과 동일
for (int i = 0; i < len - k + 1; i++)
    result += diff[i]; 

result 출력
```
> 헷갈리면 귓.

**Comment by yereumi** [comment]
### 시간복잡도 생각해보기
- N의 범위가 1 ≤ N ≤ 10,000이므로 `O(N^2)` 내에 해결해야 한다.

### 풀이 아이디어
- 배열을 오름차순 정렬한 후, 각 차를 `PriorityQueue`에 저장한다.
- `PriorityQueue`에서 N - K 만큼의 수를 `poll()`해서 `answer`에 더해준다.

### 의사코드 / 풀이 과정
```java
int[] num <- input
Arrays.sort(num)
PriorityQueue<Integer> pq = new PriorityQueue<>()
for (int i = 0 -> n - 1) {
    pq.offer(num[i + 1] - num[i]
}
int answer = 0
for (int i = 0 -> n - k) {
    answer += pq.poll()
}
print(answer)
```

**Comment by rladmstn** [comment]
### 시간복잡도 생각해보기
- 1 ≤ N ≤ 10,000
- 1 ≤ K ≤ 1,000
- 아마 최대 O(N^2)

### 풀이 아이디어
- 입력받은 좌표들에 대해 각 센서 좌표 간 거리를 우선순위큐에 저장
- 가장 거리가 가까운 것들 먼저 집중국 세워주면 신호 수신의 최소 거리 합이 됨
- k개 집중국을 세워주므로 거리의 n-k개 만큼만 poll 해서 answer에 더해주기

### 의사코드 / 풀이 과정
```java
// 입력 다 받기
PriorityQueue<Integer> pq : 각 센서 간 거리를 저장할 우선순위 큐

for(int i=0; i<n-1; i++){
     pq.add(arr[i+1]-arr[i]);
}

int answer = 0;
for(n-k개만큼){
    answer += pq.poll();
}

```

**Comment by yeo-li** [comment]
### 시간복잡도 생각해보기
- 1 ≤ N ≤ 10,000
- 1 ≤ K ≤ 1000
- 아마...  최대 시간이 2초니까 2*10^8 이고, N*K 해도 10^7이니까 O(N^2) 까지 가능하지 않을까 싶습니다.

### 풀이 아이디어
- 센서의 거리를 정렬한 후, 각 거리의 차를 구하여 다시 한 번 오름차순 정렬한다.
- 오름차순 정렬된 센서 거리의 거리의 차를 N - K개 만큼 더하면 최소 거리가 나온다.

### 의사코드 / 풀이 과정
```
int[] coordinate = 각 센서의 좌표 N개
Arrays.sort(coordinate)

int[] distance = new int[N-1]
for(int i = 1; i < N; i++){
  distance[i - 1] = coordinate[i] - coordinate[i - 1]
}
Arrays.sort(distance)

int answer = 0
for(int i = 0; i < N-k; i++) {
  answer += distance[i]
}

print(answer)
```

**Comment by chaerish** [comment]
### 시간복잡도 생각해보기
- 10^6이 최댓값이므로 O(NlogN)안에 해결하는 것이 중요하다.
- 배열을 정렬하고 -> `O(NlogN)` + N-1개의 차를 계산하고`O(N)` +` O(N-K) `만큼 차를 더하므로 =>`O(NlogN)`

### 풀이 아이디어
- K개의 집중국이 있을 때 연속된 센서 간의 차를 최소한으로 해라 => **그리디**
- 1. 센서 좌표 배열을 받아서 연속된 센서 간의 차를 구한다.
- 2. 연속된 센서 간의 차이를 오름차순으로(혹은 내림차순)으로 정렬한다.
- 3. 집중국 개수 K-1 만큼만 배열들을 더해준다.
![image](https://github.com/user-attachments/assets/11682874-1ed5-46b6-84f8-68d46df0492d)
  - 집중국 K를 세워야 한다면 센서와 센서 사이를 **K-1 회 뛰어넘을 수 있기 때문이다.** 
  - 그리고 자기 자신에만 집중국을 세운다면 거리가 0이 되는 것도 생각해야 한다.

### 의사코드 / 풀이 과정
```java
for(int i=0; i<s.length;i++) {
	s[i] = Integer.parseInt(st.nextToken());
}
Arrays.sort(s);
for(int i=0; i<minus.length;i++) {
	minus[i] = s[i+1] - s[i];
}
Arrays.sort(minus);
int answer = 0;
for(int i=0; i<N-K;i++) {
	answer+=minus[i];
}
````
[참고 자료](https://velog.io/@jkh9615/%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98-%EB%B0%B1%EC%A4%80-11000-%EA%B0%95%EC%9D%98%EC%8B%A4-%EB%B0%B0%EC%A0%95-Java-wskzqzk6)
