### ISSUE TITLE
[2주차 - 5] 가장 큰 수

### ISSUE THREAD

**Issue by Jewan1120** [T4F1/Algorithm#21]
## 문제 
- 문제 사이트: 프로그래머스 
- 문제 이름: [가장 큰 수](https://school.programmers.co.kr/learn/courses/30/lessons/42746)
- 문제 번호: 42746

### 문제 풀이 템플릿
```
### 시간복잡도 생각해보기
- 

### 풀이 아이디어
- 

### 의사코드 / 풀이 과정
- 

```

**Comment by Jewan1120** [comment]
### 시간복잡도 생각해보기
- numbers의 길이는 1 이상 100,000 이하 &rarr; 10^5이므로 O(N logN)까지 가능
- 완전 탐색이 불가능하므로 정렬만으로 해결

### 풀이 아이디어
- 배열을 특정한 정렬 기준에 맞추어 정렬 후 모든 원소 이어 붙이기
- 정렬 기준
  - `A`와 `B`가 있을 때, 각 수를 이어 붙인 `AB`와 `BA`중 어떻게 이어 붙였을 때 더 큰 수가 나오는지 비교
- 원소를 이어 붙이는 방식
  - 정수의 길이만큼 10을 곱한 후 더하는 방식
    - 원소의 길이가 가변적이기 때문에 번거로움
    - 이어 붙인 정수가 최대 10^5 x 10^3 자리가 될 수 있으므로 연산 불가
  - **기존 `int[]`를 `String[]`으로 바꾸어 `A + B`연산으로 문자열 이어 붙이기**
- 이어 붙인 문자열이 `0`으로만 이루어진 경우 `0`을 출력해줘야 함
  - `00000`을 출력하면 오답

### 의사코드 / 풀이 과정
```java
String[] strArr // 기존에 주어지는 int[]를 String으로 변환하여 저장
Arrays.sort(strArr, (o1, o2) -> (o2 + o1).compareTo(o1 + o2)) // 람다식을 이용하여 정렬 기준 정해줌
StringBuilder sb // StringBuilder를 이용해 빠른 연산
모든 문자열 append

if (sb.charAt(0) == '0') // 첫 자리가 0이라면 모든 문자열이 0
  0 반환
else
  sb.toString 반환
```

**Comment by rladmstn** [comment]
### 시간복잡도 생각해보기
- numbers의 길이는 1 이상 100,000 이하
- 최대 O(NlogN)으로 해결 필요

### 풀이 아이디어
- 숫자를 모두 String으로 형태 변형
- 두 개를 붙였을 때 더 큰 수면 앞으로 오도록 정렬됨
- 0이 입력된거는 따로 처리 필요

### 의사코드 / 풀이 과정
```java
String[] arr : 숫자들을 String으로 타입 변환한 배열
Arrays.sort(arr, (s1,s2) -> (s2+s1).compareTo(s1+s2)); // 두 개를 붙였을 때 더 큰 수면 앞으로 오도록

if(arr[0].equals("0"))
     return "0";
else
    return String.join("", arr); // 정렬된 순서대로 쭉 이어 붙여 리턴
```

**Comment by yereumi** [comment]
### 시간복잡도 생각해보기
- numbers의 길이가 1 이상 100,000 이하이므로 `O(NlogN)` 내로 해결해야 한다. 

### 풀이 아이디어
- int 배열을 String 배열로 변환한다.
- `Arrays.sort()`를 이용하여 문자열 배열의 두 수를 붙였을 때 더 큰 수가 먼저 오도록 정렬한다.
- 문자열 배열의 0번 문자열이 "0"이라면 나머지 문자열도 "0"이므로 따로 처리해준다.

### 의사코드 / 풀이 과정
```java
String[] strNumbers <- input을 문자열로 변환
Arrays.sort(strNumbers, (o1, o2) -> (o1 + o2).compareTo(o2 + o1))
StringBuilder sb = new StringBuilder()
for (String s : strNumbers) {
    sb.append(s)
}
if (sb.toString().charAt(0) == '0')
    return "0"
return sb.toString()
```

**Comment by chaerish** [comment]
### 시간복잡도 생각해보기
**O(logN)으로 해결 필요**
- 숫자 N개를 String으로 변환하기 -> O(N)
- 숫자 두개를 더했을때 큰 것 정렬하기 -> O(logN)
- 숫자 출력하기 -> O(N)
- 총 `O(logN)`
### 풀이 아이디어
- 숫자를 모두 String값으로 만들고 두개를 더해서 큰 값이 되는 것을 정렬해주면 되는 문제였다

### 의사코드 / 풀이 과정
```java
for(int num: numbers){
    list.add(String.valueOf(num));     		
}
Collections.sort(list,(a,b)->{
    return (b+a).compareTo(a+b);
});
StringBuilder result = new StringBuilder();
for(String str: list) {
    result.append(str);
}
```
```
Collections.sort(list,(a,b)->{
    return (b+a).compareTo(a+b);
});
```
가 가장 중요한 부분이 아니였을까 싶다.
#### 틀린코드 
```java
class Solution {
public String solution(int[] numbers) {
List<char[]> list = new ArrayList<>();
	for(int num: numbers){
	    char[] numCharArrays = (String.valueOf(num)).toCharArray();
	    list.add(numCharArrays);     		
	}
	Collections.sort(list,(a,b)->{
	
	 int min = Math.min(a.length, b.length);
	 for(int i=0;i < min; i++) {
	  int aV = Character.getNumericValue(a[i]);
	  int bV = Character.getNumericValue(b[i]);
	  if(aV != bV) {
	   return Integer.compare(bV, aV);
	  }
	 }
	 return Integer.compare(b[0],a[0]);
	});
	StringBuilder result = new StringBuilder();
	for(char[] c: list) {
	 result.append(new String(c));
	}
	return result.toString();
  }
}
```
- 숫자를 char 배열로 만들어서 하나씩 비교해 정렬하려고 했다
```
[3, 30, 34, 5, 9]
기댓값 〉	"9534330"
실행 결과 〉	실행한 결괏값 "9534303"이 기댓값 "9534330"과 다릅니다
````
- 이런 결과가 떠서 이유를 너무 잘 알겠는데 예외처리할게 너무 복잡해서 포기하고 답봤다

**Comment by yeo-li** [comment]
### 시간복잡도 생각해보기
- numbers의 길이는 1 이상 100,000 이하 이므로 N(logN)이 최대

### 풀이 아이디어
- number1과 number2를 stirng으로 변환해준 뒤, number1+number2 와 number2+number1의 값을 비교해주어 우선순위를 정했다.

### 의사코드 / 풀이 과정
```
int compareTo(int number1 int number2) {
  String N = String.valueOf(number1) + String.valueOf(number2);
  String M = String.valueOf(number2) + String.valueOf(number1);

  return Integer.parseInt(N) > Integer.parseInt(M) ? -1 : 1;
}

PriorityQueue pq = new PriorityQueue<Integer>((o1, o2) -> compareTo(o1, o2));

String answer = "";
while(!pq.isEmpty()) { 
  answer += String.valueOf(pq.poll());
}

print(answer);
```
