### ISSUE TITLE
[2주차 - 6] 카드 정렬하기

### ISSUE THREAD

**Issue by Jewan1120** [T4F1/Algorithm#22]
## 문제 
- 문제 사이트: 백준
- 문제 이름: [카드 정렬하기](https://www.acmicpc.net/problem/1715)
- 문제 번호: 1715

### 문제 풀이 템플릿
```
### 시간복잡도 생각해보기
- 

### 풀이 아이디어
- 

### 의사코드 / 풀이 과정
- 

```

**Comment by Jewan1120** [comment]
### 시간복잡도 생각해보기
- 1 ≤ N ≤ 100,000 &rarr; 10^5이므로 O(N logN)으로 풀이

### 풀이 아이디어
- 카드를 `그리디`한 방식으로 묶어야 함 &rarr; 작은 카드들끼리 묶기
- 배열을 오름차순으로 정렬해서 작은 것들을 꺼내기 위해 `우선순위 큐`를 이용
  - `우선순위 큐`의 `Heapify`는 O(N logN)
- `우선순위 큐`의 크기가 1이 될 때까지 이하 반복
  1. 큐에서 작은 수 2개 꺼내기
  2. 두 수를 더하고 해당 값(`sum`)을 비교 횟수(`total`)에 합
  3. 두수를 더한 값(`sum`)을 다시 `우선순위 큐`에 삽입

### 의사코드 / 풀이 과정
```java
PriorityQueue<Integer> pq // 오름차순

우선순위 큐에 데이터 입력

int total // 총 비교 횟수
while (pq.size() != 1)
  int sum = pq.poll() + pq.poll() // 가장 작은 두 수의 합
  total += sum
  pq.offer(sum)

total 출력
```

**Comment by chaerish** [comment]
### 시간복잡도 생각해보기
- O(NlogN)에 끝내야한다.

### 풀이 아이디어
- 최소끼리 더하면 최소가 된다는 그리디적 상상..
- 더해준 최솟값 합도 다시 더해줘야 하므로 우선순위 큐에 넣어서 항상 최소상태 유지

### 의사코드 / 풀이 과정
```java
for(int i=0; i<N-1; i++) {
  Integer a = pq.poll();
  Integer b = pq.poll();
  Integer sum = a+b;
  answer += (sum);
  pq.add(sum);
}

```

#### 틀린 코드 
```java
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.Arrays;

public class BJ1715 {
	static Integer arr [];
	public static void main(String [] args) throws NumberFormatException, IOException {
		BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
		int N = Integer.parseInt(br.readLine());
		arr = new Integer [N];
		for(int i=0; i<N; i++) {
			arr[i] = Integer.parseInt(br.readLine());
		}
		Arrays.sort(arr);
		long answer=0;
		for(int i=0; i<N-1; i++) {
			arr[i+1] =arr[i] + arr[i+1];
			answer+= arr[i+1];
			Arrays.sort(arr);
		}
		System.out.println(answer);
	}
}
```
메모리초과, 시간 초과
정렬을 계속해주니까 `O(N^2)` -> 극복방법: 우선 순위 큐 
예시: 
```
6
1
1
1
1
100
100
```
[2, 1, 1, 100, 100] -> 원래 [1, 1, 2, 100, 100] 가 되어야 함.
일때 내 코드대로라면 계속해서 최소상태를 보장해주지 않지만, 우선순위 큐를 사용하면 최신상태를 보장해준다.

**Comment by rladmstn** [comment]
### 시간복잡도 생각해보기
- 1 ≤ N ≤ 100,000
- 최종 시간 복잡도는 `O(NlogN)`으로 해결 필요

### 풀이 아이디어
- 작은 것들끼리 묶어야 함
- 계속 비교 횟수를 갱신하며 최소인 두 개를 더해주면 됨
- result 변수에 poll 한 두 개의 값을 계속 더해주면 답
- 반복 정렬은 시간초과 발생
- 자동 오름차순 정렬을 위해서 PriorityQueue 사용

### 의사코드 / 풀이 과정
```java
PriorityQueue<Integer> pq : 우선순위 큐에 카드 개수 저장

while(pq.size() > 1){ // qp에 요소가 1개 남을 때까지 반복
      int a = pq.poll();
      int b = pq.poll();
      result += a+b;
      pq.add(a+b);
}
```

**Comment by yereumi** [comment]
### 시간복잡도 생각해보기
- N의 범위가 1 ≤ N ≤ 100,000 이므로 `O(NlogN)` 내로 해결해야 한다.

### 풀이 아이디어
- 최소 비교 횟수를 구하기 위해서 오름차순 정렬을 해야 한다.
- 초기 값들을 `PriorityQueue`에 저장하고, 마지막 한 개가 남을 때까지 두 개씩 `poll()`한 값을 더해준다.

### 의사코드 / 풀이 과정
```java
PriorityQueue<Integer> pq <- input()
long answer = 0
while (pq.size() != 1) {
    int a = pq.poll()
    int b = pq.poll()
    pq.offer(a + b)
    answer += a + b
}
print(answer)
```
