### ISSUE TITLE
[2주차 - 7] 아이들과 선물 상자

### ISSUE THREAD

**Issue by Jewan1120** [T4F1/Algorithm#23]
## 문제 
- 문제 사이트: 백준
- 문제 이름: [아이들과 선물 상자](https://www.acmicpc.net/problem/23757)
- 문제 번호: 23757

### 문제 풀이 템플릿
```
### 시간복잡도 생각해보기
- 

### 풀이 아이디어
- 

### 의사코드 / 풀이 과정
- 

```

**Comment by Jewan1120** [comment]
### 시간복잡도 생각해보기
- 1 &le; M &le; N &le; 10^5 &rarr; O(N logN)으로 해결

### 풀이 아이디어
- `현재 선물이 가장 많이 담겨있는 상자에서 각자 원하는 만큼 선물을 가져간다.`이므로 최댓값을 사용해야 함
- `우선순위 큐`를 이용하여 최댓값을 조회하기
-  1번 아이부터 M번 아이까지 차례대로 아이가 최댓값의 상자에서 원하는 만큼의 선물을 못 가져간다면 `0` 출력
- 선물을 가져갈 수 있으면 상자에서 선물을 빼고 다시 `우선순위 큐`에 상자를 삽입
- 모든 아이들을 순회했다면 `1` 출력

### 의사코드 / 풀이 과정
```java
PriorityQueue<Integer> pq // 내림차순

상자 입력받아서 우선순위 큐에 삽입

for ( i = 0 < m)
  int w // 아이가 원하는 선물의 양
  // 아이가 원하는 선물의 양을 최댓값의 상자에서 줄 수 없을 경우
  if (pq.peek() < w)
    0 출력
    return // 종료

// 모든 아이들의 순회가 완료되었다면
1 출력
```

**Comment by rladmstn** [comment]
### 시간복잡도 생각해보기
- 1 <= M <= N <= 10^5
- 최종 시간 복잡도는 최대 O(NlogN)

### 풀이 아이디어
- 내림차순 c 배열 정렬 -> PriorityQueue 사용하기
- 순서대로 poll 하며 현재 원하는 수보다 적으면 무조건 0 출력 후 종료
- 이전 사람의 선물 상자에서 더 가져올 수 있으므로 현재 아이가 가져간 수를 뺀 나머지를 다시 큐에 삽입

### 의사코드 / 풀이 과정
```java
PriorityQueue<Integer> pq : 선물 상자 목록 우선순위 큐

for(int i=0; i<m; i++){
    int curMax = pq.poll(); // 현재 상자의 최대 선물 수
    int curWant = w[i]; // 현재 원하는 개수
    if(curMax < curWant) 
           0 출력
    pq.add(curMax-curWant); // 남은 것들 다시 삽입
}

다 완료되면 1 출력
```

**Comment by yereumi** [comment]
### 시간복잡도 생각해보기
- N과 M의 범위가 M ≤ N ≤ 10^5 이므로` O(NlogN)` 내로 해결해야 한다.
 
### 풀이 아이디어
- 선물 상자에 들어있는 상자의 개수(gift)를 내림차순 `PriorityQueue`에, 아이가 원하는 선물의 개수를 `Deque`에 저장한다.
- 아이 번호순으로 상자의 개수(num)를 poll()한 값과 아이가 원하는 선물의 개수를 비교한다.
  - gift.poll() < num.poll() $\rightarrow$ break

### 의사코드 / 풀이 과정
```java
PriorityQueue gift = new PriorityQueue<>((o1, o2) -> o2.compareTo(o1)) <- input()
Deque num = new ArrayDeque<>() <- input()
while (!num.isEmpty()) {
    int giftNum = gift.poll()
    int wantNum = num.poll()
    int answer = 1
    if (giftNum < wantNum) {
        answer = 0
        break
    }
}
print(answer)
```

**Comment by yeo-li** [comment]
### 시간복잡도 생각해보기
- 1 <= M <= N <= 100,000
- 이므로 O(NlogN) 가능

### 풀이 아이디어
- 현재 가장 선물이 많이 담겨있는 상자에서 가져가므로 우선순위 큐를 사용해 선물 상자의 선물 개수를 내림차순으로 add한다.
- 그리고 아이들이 선물을 가져갈 때마다 우선순위큐를 업데이트 한다.
- 예시 : result = pq.poll() - child; pq.add(result);
- 그리고 result가 음수이면 로직을 멈추고 0을 출력한다. 그렇지 않으면 1을 출력한다.

### 의사코드 / 풀이 과정
```
presents = PriorityQueue((o1, o2) -> o2 - o1) <- input();
child = int[] <- input();
int answer = 1;
for(int i = 0; i < M; i++) {
  present = presents.poll();
  result = present - child[i];
  if(result < 0) {
    answer = 0;
    break;
  }
  presents.add(result);
}

print(result);
```

**Comment by chaerish** [comment]
### 시간복잡도 생각해보기
- 10의 최대가 5승이기 때문에 O(NM)으로 풀수 없고 O(NlogM)으로 풀어야 하는 문제였음.
- 반복문 M번 동안 우선순위 큐를 사용하고 정렬하므로 `O(MlogN)`
### 풀이 아이디어
- 계속 최신으로 큰 값을 갱신해줘야 해서 우선순위 큐 사용
- M번 반복문 돌리며 **아이들이 원하는 값보다 선물상자에 있는 값이 작으면 바로 0 리턴**
- 만약 무사히 M번동안 선물 조건이 충족했다면 1리턴 

### 의사코드 / 풀이 과정
```java
for(int i=0; i<M; i++) {
	int maxBox = hpq.poll();
	int give = Integer.parseInt(st.nextToken());
	if(maxBox < give) {
		System.out.println(0);
		return;
	}
	if(maxBox>give) { //선물이 남았으면 
		hpq.add(maxBox - give);
	}
}	

```

#### 틀린코드, 틀린이유
```java
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.util.PriorityQueue;
import java.util.StringTokenizer;
import java.util.Collections;

public class Main {
	static PriorityQueue<Integer> hpq = new PriorityQueue<>(Collections.reverseOrder());
	static PriorityQueue<Integer> gpq = new PriorityQueue<>(Collections.reverseOrder());
	static int answer = 1;
	public static void main(String [] args) throws Exception {
		BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
		StringTokenizer st = new StringTokenizer(br.readLine());
		int N = Integer.parseInt(st.nextToken());
		int M = Integer.parseInt(st.nextToken());
		
		st = new StringTokenizer(br.readLine());
		for(int i=0; i<N; i++) {
			hpq.add(Integer.parseInt(st.nextToken()));
		}
		st = new StringTokenizer(br.readLine());
		for(int i=0; i<M; i++) {
			gpq.add(Integer.parseInt(st.nextToken()));
		}
		while(!gpq.isEmpty()) {
			int maxBox = hpq.poll();
			int give = gpq.poll();
			if(maxBox < give) {
				answer = 0;
				break;
			}
			if(maxBox>give) { //선물이 남았으면 
				hpq.add(maxBox - give);
			}
		}			
		System.out.println(answer);
	}
}
```
##### 틀린이유
아이들의 선물 값도 우선순위 큐에 담고 그거마저 O(logN)의 정렬을 해서 시간초과가 남.
```java
hpq.add => O(logN)
hpq.poll => O(logN)
gpq.poll => O(logM)
```
그리고 gpq가 비어질때까지 도므로 M 
이 모든게 M번 반복하므로
`O(M*(2logN + logM)) = O(MlogN+MlogM) `
