### ISSUE TITLE
[3주차 - 2] 문자열 폭발

### ISSUE THREAD

**Issue by Jewan1120** [T4F1/Algorithm#31]
## 문제 
- 문제 사이트: 백준
- 문제 이름: [문자열 폭발](https://www.acmicpc.net/problem/9935)
- 문제 번호: 9935

### 문제 풀이 템플릿
```
### 시간복잡도 생각해보기
- 

### 풀이 아이디어
- 

### 의사코드 / 풀이 과정
- 

```

**Comment by Jewan1120** [comment]
### 시간복잡도 생각해보기
- 1 &le; 문자열의 길이 &le; 1,000,000 &rarr; 10^6이므로 O(N logN)으로 해결
- 2초

### 풀이 아이디어
- 정규 표현식, 인덱스 찾기와 같은 `완전탐색`으로도 접근할 수 있지만 시간 초과
- 따라서 문자열을 선형적으로 탐색하면서 폭발할 수 있는지 확인해야 함
- 스택 2개를 이용해서 문자열을 비교
  - 임시 스택에 폭발할 문자가 채워졌을 경우 해당 스택을 비움
  - 폭발할 문자가 채워지지 못했다면 다시 기존 스택에 문자 삽입
 
### 의사코드 / 풀이 과정
```java
def main()

char[] cArr    // 입력된 문자열을 문자 배열로 변경
char[] check // 폭발할 문자열

Deque<Character> dq      // 문자를 저장할 스택
Deque<Character> temp // 폭발할 수 있는지 확인할 스택

// 모든 문자 비교
for(i = 0 ~ cArr.length)
   dq.offerLast(cArr[i]); // 등장하는 문자를 스택에 삽입
   int idx = check.length - 1 // 폭발할 문자열인지 뒤부터 확인
    // 폭발할 수 있는 문자열을 만들 수 있는지 뒤에서부터 확인
    while (check[idx] == dq.peekLast())
      temp.offerLast(dq.pollLast());
      idx--;
   
    // 폭발 가능하다면
    if (temp.size() == check.length)
      temp.clear(); // 폭발
   
    // 폭발하지 않은 문자들은 다시 기존 스택에 삽입
    while (!temp.isEmpty())
        dq.offerLast(temp.pollLast());

조건에 맞게 스택에서 꺼내서 문자 출력
```

**Comment by rladmstn** [comment]
### 시간복잡도 생각해보기
- 문자열의 길이 N : 1 <= N <= 1,000,000
- 최종 시간 복잡도 : `2 * O(NlogN)` 내에 해결 필요

### 풀이 아이디어
- `StringBuilder`를 stack 역할처럼 사용하기
- 입력받은 문자열을 모두 순회하며 StringBuilder에 append
- append 한 상태에서 끝 부분의 substring을 구했을 때 폭발 문자열과 일치하면 StringBuilder에서 폭발 문자열 크기만큼 remove
- 결과적으로 StringBuilder 길이가 0이면 "FRULA" 출력

### 의사코드 / 풀이 과정
```java
String str : 문자열
String bombStr : 폭발 문자열
StringBuilder sb : 스택 역할의 StringBuilder

for(int i=0; i<str.length(); i++){
  sb.append(str.charAt(i)); // 현재 인덱스의 문자 append
  if(스택 길이 < 폭발 문자열 길이){
       continue; // 비교 필요 없으므로 넘어감
  }

  while(sb.substring(맨 끝부터 bombStr 길이만큼).equals(bombStr)){
      sb.delete(맨 끝부터 bombStr 길이만큼);
  }

  System.out.println(sb); // 0이면 "FRULA" 출력
}
```

**Comment by chaerish** [comment]
### 시간복잡도 생각해보기
- 문자열의 총 길이가 10^6 이고 제한시간 2초이므로 2 X 10^8 개의 연산이 가능하다.
- 따라서 O(N^2)에서는 10^12 개의 연산이 필요하므로 제한시간 초과가 되므로 `O(NlogN)`에 해결해야 한다.

### 풀이 아이디어
- replace.All() 을 처음에 사용했으나, String은 불변 객체이므로  replaceAll은 내부적으로 새로운 문자열을 생성해 원본 문자열을 대체한다. 따라서 문자열의 크기가 10^6처럼 매우 크거나 대체 작업이 여러번 수행 될 경우에는 새로운 문자열 객체가 과도하게 사용 돼 메모리를 초과한다.
- 메모리를 효율적으로 사용하기 위해서는 `Stack`의 push, pop을 사용한다. 
- 문자열을 charAt으로 나눠서 계속 stack에 푸쉬하다가, `bomb`의 문자길이와 비슷해지면 그때부터 비교작업을 수행한다.
- 비교작업: **(Stack의 현재 사이즈 - bomb의 사이즈) + j (j는 0부터 bomb의 길이까지) char이 같은지 확인한다.**
- 하나라도 다르다면 flag를 false로 둔다.

### 의사코드 / 풀이 과정
```java
stack.push(carr[i]);
if(stack의 사이즈가 bomb의 사이즈보다 크거나 같다면):
    for(j=0부터 bomb의 사이즈까지):
          if(stack.get(스택 사이즈 - bomb사이즈 +j) != bomb.charAt(j)) -> 하나라도 다르면 false;
        만약 같다면: 
           for(j=0부터 bomb의 사이즈까지):
                  stack.pop(); //스택에서 제거 
```
#### 틀린 아이디어
```java
String 문자열 = “”;
String 폭발문자열 = “”;

while(폭발문자열이 더이상 없을때까지): -> 시간초과 가능성있음 
       if(문자열.contain(폭발문자열)): 
		문자열 = 문자열 - 폭발문자열 

```
#### 오류난 코드
```java
import java.io.BufferedReader;
import java.io.InputStreamReader;
public class 문자열_폭발 { 
	public static void main(String [] args) throws Exception {
		BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
		String str = br.readLine();
		String bomb = br.readLine();
		while(true) {
			if(!str.contains(bomb)) {
				break;
			}
			str = str.replaceAll(bomb, "");
		}
		if(str.isBlank() || str.isEmpty()) {
			System.out.println("FRULA");
			return;
		}
		System.out.println(str);
	}
}
```
 추가시간이 2초인데 시간문제는 아닌것같고 `replace.All()` 때문에 메모리초과 
<img width="617" alt="스크린샷 2024-12-08 18 02 15" src="https://github.com/user-attachments/assets/7457f70f-01d4-4a5e-831e-da644f0cd25e">

**Comment by yeo-li** [comment]
### 시간복잡도 생각해보기
- 최대 시간 복잡도는 `O(NlogN)`

### 풀이 아이디어
- stack을 이용해서 넣다가 폭탄의 길이와 같아지면 비교하고 같으면 폭파시킨다.

### 의사코드 / 풀이 과정
```
for(int i = 0; i < input.length(); i++) {
	int count = 0;
	stack.push(input.charAt(i));
			
	if(stack.size() >= boomer.length()) {				
		for(int j = 0; j < boomer.length(); j++) {
			if(stack.get(stack.size() - boomer.length() + j) == boomer.charAt(j)) {
				count++;
			}
		}
				
		if(count == boomer.length()) {
			for(int k = 0; k < boomer.length(); k++) {
				stack.pop();
			}
		}
	}
}
```

**Comment by yereumi** [comment]
### 시간복잡도 생각해보기
- 1<=N<=1,000,000 이므로 `NlogN` 내로 해결해야 한다.

### 풀이 아이디어
- 문자열의 문자를 하나씩 `StringBuilder`에 저장해서, 폭발 문자열과 같은 부분을 제거한다.

### 의사코드 / 풀이 과정
```java
for (char c : str.toCharArray()) {
sb.append(c);

if (sb.length() >= expLength) {
    if (sb.substring(sb.length() - expLength).equals(explosion)) {
        sb.delete(sb.length() - expLength, sb.length());
         }
     }
}
```

### 틀린코드
메모리 초과 발생: String은 불변 자료형이라 str = str.replaceAll(Pattern.quote(explosion), ""); 이 코드에서 메모리에 계속 쌓인다.
→ `StringBuilder`에 저장
```java
BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
String str = br.readLine();
String explosion = br.readLine();
while (str.contains(explosion)) {
	str = str.replaceAll(Pattern.quote(explosion), "");
}
System.out.println(str.length() == 0 ? "FRULA" : str);
```
