### ISSUE TITLE
[3주차 - 3] 팰린드롬 분할

### ISSUE THREAD

**Issue by Jewan1120** [T4F1/Algorithm#32]
## 문제 
- 문제 사이트: 백준 
- 문제 이름: [팰린드롬 분할](https://www.acmicpc.net/problem/1509)
- 문제 번호: 1509

### 문제 풀이 템플릿
```
### 시간복잡도 생각해보기
- 

### 풀이 아이디어
- 

### 의사코드 / 풀이 과정
- 

```

**Comment by rladmstn** [comment]
### 시간복잡도 생각해보기
- 문자열 최대 길이는 2500이므로 O(N^2) 가능

### 풀이 아이디어
- `dp[i]` : 인덱스 i까지의 문자열들 중 팰린드롬 분할 개수의 최솟값
- 0~문자열 길이만큼 순회(i)하며, 해당 인덱스까지의 팰린드롬 분할 개수를 구해 dp[i]에 저장함
- 인덱스를 0부터 i까지 순회(j)하며, index j~i 가 팰린드롬이면 dp값 갱신
  - j가 0이면 팰린드롬은 한 개이므로 1으로 초기화
  - `value 1` : `dp[i]+1` : i-1 인덱스까지의 구한 dp값에 현재 문자가 그냥 붙기만 하는 것이므로 +1
  - `value 2` : `dp[j-1]+1` : 현재 문자가 팰린드롬에 포함되는 경우, 팰린드롬의 직전 문자 인덱스(j-1]의 dp값 + 현재 문자가 포함된 팰린드롬 (1)
  - 최솟값을 구하는 것이므로, value1과 vlaue2를 비교해 더 작은 값을 dp[i] 값으로 갱신

### 의사코드 / 풀이 과정
```java
isPalindrome(char[] arr, int start, int end) : 범위 내 팰린드롬 판정 함수
char[] arr : 입력 받은 문자열
int[] dp : dp 배열

for(int i=1; i<문자열 길이만큼){
  dp[i] = dp[i]+1; // 그냥 arr[i] 붙인 값으로 초기화
  for(int j=0; j<=i; j++){
    if(isPalindrome(arr, j, i){
      if(j == 0) dp[i] = 1; // 팰린드롬의 시작 인덱스가 0이면 최솟값은 1개
     else{
        dp[i] = Min(dp[i], dp[i-1]+1); // value1, value2 비교해 최솟값으로 갱신
     }
    }
  }
}

sout(dp[arr 마지막 문자 인덱스]);
```
