### ISSUE TITLE
[4주차 - 5] 암호

### ISSUE THREAD

**Issue by Jewan1120** [T4F1/Algorithm#47]
## 문제 
- 문제 사이트: 백준
- 문제 이름: [암호](https://www.acmicpc.net/problem/1394)
- 문제 번호: 1394

### 문제 풀이 템플릿
```
### 시간복잡도 생각해보기
- 

### 풀이 아이디어
- 

### 의사코드 / 풀이 과정
- 

```

**Comment by yeo-li** [comment]
### 시간복잡도 생각해보기
- 완전 탐색을 했을 때, 100^100 이 나오므로, 완전탐색으로 해결하면 안됨.
- 줄일 수 있는 모든 것을 줄이면 된다.

### 풀이 아이디어
- `string.length()`진수라고 생각하면 편하다.
- 암호의 가장 마지막 문자부터 역순회를 하며 문자집합에서 몇 번째 수인지 구하여 `string.length()^(string.length() - index - 1)`과 곱해준다. 가장 앞 부분까지 그 결과를 더해준다.
- 숫자가 `900528` 이상이 된다면 모듈러 연산을 해주어 값을 줄여준다.
- 문자가 몇 번째 위치에 있는지 구하기 위해선 항상 순회를 해야한다. 이 시간을 줄여주기 위하여 `HashMap<Character, Integer>`을 사용하여 시간을 최적화 해준다.

### 의사코드 / 풀이 과정
```java
char[] arr = br.readLine().toCharArray();
Map<Character, Integer> charMap = new HashMap<>();
char[] pw = br.readLine().toCharArray();
		
for(int i = 0; i < arr.length; i++) {
	charMap.put(arr[i], i+1);
}
		
int a = 1;
int r = arr.length;
int result = 0;
for(int i = pw.length - 1; i >= 0; i--) {
	result = (result + (a*charMap.get(pw[i]))%MOD)%MOD;
	a = (a*r)%MOD;
}
```

**Comment by yereumi** [comment]
### 시간복잡도 생각해보기
- N<=100 이므로 완전탐색이 아닌 방법으로 해결해야 한다.

### 풀이 아이디어
- `HashMap`에 문자와 순서를 저장한다.
- 진법 변환의 원리로 해결한다.
  - cnt = ((1번째 문자의 위치) * 문자집합의 크기) + (2번째 문자의 위치)) * 문자집합의 크기 ...

### 의사코드 / 풀이 과정
```java
for (int i = 0; i < passwordSize; i++) {
	cnt += (hm.get(Character.toString(password.charAt(i))) + 1);
	if (i < passwordSize - 1) {
		cnt *= charSetSize;
	}
	cnt = cnt % 900528;
}
```

**Comment by Jewan1120** [comment]
### 시간복잡도 생각해보기
- 암호의 길이는 최대 1,000,000자
- 암호에 사용할 수 있는 문자의 종류는 최대 100가지
- 완전 탐색 보다는 조합론

### 풀이 아이디어
- 특정 문자열이 나올 때까지 순회 &rarr; 어떤 문자열이 몇 번째에 등장하는지 수학적으로 계산 가능
- 타겟으로 하는 문자에 대해서 각 인덱스에 있는 문자가 등장하는 순서 더하기 &rarr; O(N)
  - 한 바퀴 순회하면 인덱스가 바뀜

### 의사코드 / 풀이 과정
```java
HashMap<Character, Integer> hm = new HashMap<>(); // 각 문자가 몇 번째 순서에 등장하는 지
for (int i = 0; i < str.length(); i++)
    hm.put(str.charAt(i), i + 1);
char[] target = br.readLine().toCharArray();
int result = 0;
int len = target.length;
for (int i = 0; i < len; i++) {
    result *= hm.size(); // 싸이클
    result += hm.get(target[i]); // 등장 순서
    result %= MOD; // 모듈러 연산
}
```

**Comment by rladmstn** [comment]
### 시간복잡도 생각해보기
- 암호 길이 최대 최대 1,000,000자
- N <= 100이 되므로 완탐은 불가

### 풀이 아이디어
- 인덱스 별 문자 순회 횟수(?) 구하기
- Map<Character, Integer> map : <문자, 순서> 저장

### 의사코드 / 풀이 과정
```java
Map<Character, Integer> map : <문자, 순서> 저장
int base : 가능한 문자 개수

long result = 0;
for(int i=0; i<암호길이; i++){
   result = (result * base + map.get(password의 현재 문자)) % MOD;
}
```
