### ISSUE TITLE
[4주차 - 6] 춘배가 선물하는 특별한 하트

### ISSUE THREAD

**Issue by Jewan1120** [T4F1/Algorithm#48]
## 문제 
- 문제 사이트: 백준
- 문제 이름: [춘배가 선물하는 특별한 하트](https://www.acmicpc.net/problem/30408)
- 문제 번호: 30408

### 문제 풀이 템플릿
```
### 시간복잡도 생각해보기
- 

### 풀이 아이디어
- 

### 의사코드 / 풀이 과정
- 

```

**Comment by yeo-li** [comment]
### 시간복잡도 생각해보기
- N의 최댓값이 10^18 이므로, 완전 탐색 불가.
- O(logN) 으로 탐색하며 추가로 최적화 해야한다.

### 풀이 아이디어
- `HashSet<Long>`을 사용하여 하트 N을 쪼갠 모든 무게를 저장.
- `HashSet`에 값을 add 하기 전에, `contains`를 하여 있다면 재귀함수 종료.
- 값이 1이거나 M보다 작더라도 재귀 함수 종료.

### 의사코드 / 풀이 과정
```java
void rAdd(long N) {
  if(set.contains(N)) return;
  set.add(N);
  if(N == 1 || N <= M) return;
  if(N%2 == 0) {
    rAdd(N/2);
  } else {
    rAdd((N-1)/2);
    rAdd((N+1)/2);
  }
}
```

**Comment by yereumi** [comment]
### 시간복잡도 생각해보기
- 1 <= M <= N <= 10^18 이므로 완전탐색이 아닌 다른 방법으로 해결해야 한다.

### 풀이 아이디어
- N에서 M으로 나누면서 생기는 숫자들을 `HashSet`에 저장한다.
- 재귀적으로 돌면서 만약 `HashSet`에 숫자가 이미 존재하면 더이상 나누지 않고 return 한다.
- `HashSet`에 M이 존재하면 "YES"를, 존재하지 않으면 "NO"를 출력한다.

### 의사코드 / 풀이 과정
```java
if (set.contains(n) || n < 1)
	return;
set.add(n);
if (n / 2 == 0) devide(n / 2);
else {
	devide((n - 1) / 2);
	devide((n - 1) / 2 + 1);
}
```

**Comment by Jewan1120** [comment]
### 시간복잡도 생각해보기
- 1 &le; M &le; M &le; 10^18 &rarr; O(log N)으로 구현

### 풀이 아이디어
- N을 절반으로 나눠서 M을 만들면 되는 문제 &rarr; 절반씩 재귀로 진행
- 중복된 값이 발생할 수 있으므로 중복 처리를 위한 `HashSet`을 사용

### 의사코드 / 풀이 과정
- 해당 코드를 재귀적으로 호출하고 마지막에 M값이 존재하는지 확인
```java
private static void isPossible(long A) {
    if (hs.contains(A))
        return;
    hs.add(A);
    if (A % 2 == 0)
        isPossible(A / 2);
    else {
        isPossible((A - 1) / 2);
        isPossible((A - 1) / 2 + 1);
    }
}
```

**Comment by rladmstn** [comment]
### 시간복잡도 생각해보기
- 1<= M, N <= 10^18
- O(logN)으로 해야됨

### 풀이 아이디어
- 나왔던 숫자들을 set에 저장하기
- 재귀 방식 사용해 나눌 수 있을 때까지 나누고 최종으로 set에 m이 포함됐으면 "YES", 아니면 "NO"

### 의사코드 / 풀이 과정
```java
Set<Long> set : 나눠진 숫자 결과들 저장

    private static void divide(long n) {
        // set에 이미 n값이 포함되어있으면 return; 

        set.add(n);
        if (n % 2 == 0) {
            divide(n / 2);
        } else {
            divide((n - 1) / 2);
            divide((n - 1) / 2 + 1);
        }
    }
```
