### ISSUE TITLE
[4주차 - 7] 생태학

### ISSUE THREAD

**Issue by Jewan1120** [T4F1/Algorithm#49]
## 문제 
- 문제 사이트: 백준 
- 문제 이름: [생태학](https://www.acmicpc.net/problem/4358)
- 문제 번호: 4358

### 문제 풀이 템플릿
```
### 시간복잡도 생각해보기
- 

### 풀이 아이디어
- 

### 의사코드 / 풀이 과정
- 

```

**Comment by yeo-li** [comment]
### 시간복잡도 생각해보기
- 최대 1,000,000개가 입력 되므로, O(NlogN) 시간에 해결해야함.

### 풀이 아이디어
- `TreeMap`을 사용하여 이름을 사전순으로 정렬, `treeMap.getOrDefault()`를 사용하여 새로 추가되는 값은 1로, 기존의 값엔 +1을 하여 몇 번 반복되는지 저장.
- 전체 나무 수와 treeMap의 value 값의 비율을 구하여 백분율 구하기
- 근데 문제에서는 반올림하라고 했는데, 사실은 그냥 절삭이었음... 

### 의사코드 / 풀이 과정
```java
String tree = "";
int cnt = 0;
while(true) {
	tree = br.readLine();
	if(tree == null) break;
	trees.put(tree, trees.getOrDefault(tree, 0) + 1);
	cnt++;
}
		
for(String t: trees.keySet()) {
	int value = trees.get(t);
	double result = (double)value/cnt*100;
	System.out.printf("%s %.4f\n", t, result);
}
```

**Comment by yereumi** [comment]
### 시간복잡도 생각해보기
- N <= 1,000,000 이므로 `O(NlogN)` 내로 해결해야 한다.

### 풀이 아이디어
- 정렬 가능한 해시맵이 필요하므로 `TreeMap`을 사용한다.
- `TreeMap`에 저장하고, 퍼센트를 계산해서 `StringBuilder`에 추가한다.

### 의사코드 / 풀이 과정
```java
while ((tree = br.readLine()) != null) {
	m.put(tree, tm.getOrDefault(tree, 0) + 1);
	total++;
}

for (String treeName : tm.keySet()) {
	double percent = (double) tm.get(treeName) / total * 100;
	sb.append(treeName + " " + String.format("%.3f", percent) + "\n");
}
```

**Comment by Jewan1120** [comment]
### 시간복잡도 생각해보기
- 최대 1,000,000그루의 나무 &rarr; 10^6이므로 O(N logN)

### 풀이 아이디어
- 전체 나무의 수와 각 나무의 빈도를 저장
- 나무의 이름을 사전 순으로 출력해야 하기 때문에 `TreeMap`으로 값을 저장
- 소수점 4째자리까지 반올림
  ```java
  double per = (double) (tm.get(name) * 100) / cnt;
  String.format("%.4f", per)
  ```

### 의사코드 / 풀이 과정
```java
while ((str = br.readLine()) != null) {
    tm.put(str, tm.getOrDefault(str, 0) + 1);
    cnt++;
}
StringBuilder sb = new StringBuilder();
for (String name : tm.keySet()) {
    double per = (double) (tm.get(name) * 100) / cnt;
    sb.append(name).append(" ").append(String.format("%.4f", per)).append("\n");
}
```
> Mac은 (str = br.readLine()) != null) 로 종료 조건이 되지만 Windows는 꾸져서 (!str = br.readLine()).equals(""))로 해야 함.. 백준 컴파일러가 Windows 차별

**Comment by rladmstn** [comment]
### 시간복잡도 생각해보기
- 최대 1,000,000 => O(NlogN) 해결 필요

### 풀이 아이디어
- Map<String, Integer> map : <나무이름, 등장횟수>로 저장
- TreeMap 사용해 나무 이름 정렬 상태로 만들기

### 의사코드 / 풀이 과정
```java
long total = 0;
while(true){
    String name = in.readLine();
    if(name == null)
         break;
    map.put(name, map.getOrDefault(name, 0)+1);
    total ++;
}
for(String name : map.keySet()){
   float rate = (float)map.get(name) / total * 100;
   System.out.printf("%s %.4f\n",name,rate);
}
```
