### ISSUE TITLE
[5주차 - 2] 하노이 탑 이동 순서

### ISSUE THREAD

**Issue by Jewan1120** [T4F1/Algorithm#54]
## 문제 
- 문제 사이트: 백준
- 문제 이름: [하노이 탑 이동 순서](https://www.acmicpc.net/problem/11729)
- 문제 번호: 11729

### 문제 풀이 템플릿
```
### 시간복잡도 생각해보기
- 

### 풀이 아이디어
- 

### 의사코드 / 풀이 과정
- 

```

**Comment by yereumi** [comment]
### 시간복잡도 생각해보기
- 신경쓰지 않아도 된다.

### 풀이 아이디어
- N개의 탑에서 위에 있는 N-1개의 원판을 하나의 탑으로 생각한다.
- N-1개의 원판을 1->2로 옮긴다. (재귀)
- 1에 있는 나머지 1개의 원판을 1->3으로 옮긴다.
- N-1개의 원판을 다시 2->3으로 옮긴다. (재귀)
- N이 1일 때 재귀함수를 return한다.

### 의사코드 / 풀이 과정
```java
public static void hanoi(int num, int start, int mid, int end) {
	if (num == 1) {
		sb.append(start + " " + end + "\n");
		cnt++;
		return;
	}
	hanoi(num - 1, start, end, mid);
	sb.append(start + " " + end + "\n");
	cnt++;
	hanoi(num - 1, mid, start, end);
}
```

**Comment by Jewan1120** [comment]
### 시간복잡도 생각해보기
- 구현 문제라 딱히 신경 쓰지 않음

### 풀이 아이디어
- 맨 위의 원판을 움직이는 것은 예측하기 어려움
- 맨 아래 원판은 항상 `원판이 있던 자리 → 3`으로 움직임
- 따라서 재귀적으로 맨 아래 원판부터 미리 결정하고 그 위에 있던 원판들은 다른 원판으로 보내기

### 의사코드 / 풀이 과정
```java
def main
  Call recursive(n, 1, 2, 3) 

def recursive(깊이, s, m, e)
  if (깊이 == 1) // 마지막 원판일 경우
     s → e
     return
  recursive(깊이 -1, s, e, m) // 마지막 원판 위의 원판들을 다른 위치로 이동
  s → e
  recursive(깊이 -1, m, s, e) // 마지막 원판 위의 원판을 3번 자리로 이동 
```

**Comment by yeo-li** [comment]
### 시간복잡도 생각해보기
- 시간복잡도는 고려하지 않았습니다.

### 풀이 아이디어
- 사실 이해가 잘 안갑니다...
- 그래도 이동 횟수는 `2^N - 1` 라는 사실을 압니다.

### 의사코드 / 풀이 과정
```java
void rHanoi(int N, int from, int to, int temp) {
	if(N == 0) return;
	rHanoi(N-1, from, temp, to);
	sb.append(from + " " + to).append("\n");
	rHanoi(N-1, temp, to, from);	
}
```

**Comment by rladmstn** [comment]
### 시간복잡도 생각해보기
- 1 ≤ N ≤ 20
- 생각 X

### 풀이 아이디어
- 맨아래 판을 제외한 나머지 N-1개 판들의 이동을 재귀로 처리
- 1 -> 2 : 맨 아래 판 제외한 나머지 n-1개 판을 2로 이동
- 1 -> 3 : 맨 아래 판을 3으로 이동 
- 2 -> 3 : 남은 n-1개를 다시 3으로 이동
- 위를 재귀 과정으로 반복
- parameter 값이 1이면 재귀 종료

### 의사코드 / 풀이 과정
private static void hanoi(int x, int start, int mid, int end){
        if(x == 1) {
            answer.append(start).append(" ").append(end).append("\n");
            return;
        }
        hanoi(x-1, start, end, mid);
        answer.append(start).append(" ").append(end).append("\n");
        hanoi(x-1, mid, start, end);
    }

**Comment by chaerish** [comment]
### 시간복잡도 생각해보기
- 신경 X
### 풀이 아이디어
- `Hanoi(n)  = 2xHanoi(n-1) +1`
- n개의 원판을 이동시키기 위해 A -> B 로 n-1개를 이동시키고,Hanoi(n-1)
- A -> C 가장 큰 원판이 C로 이동하고, (Hanoi(1))
- B -> C 다시 B에 있는 n-1개를 이동시키는 것은 Hanoi(n-1)이다. 
- 이것을 재귀적으로 처리한다. 
- count: 2^n -1 
### 의사코드 / 풀이 과정
```java
private static void hanoi(int N, int start, int mid, int to) {
  if (N == 1) { //이동해야할 원반의 수가 1개일때
      sb.append(start).append(" ").append(to).append("\n");
      return;
  }
  // A -> B 로 옮길 때. N-1개를 A에서 B로 이동
  hanoi(N - 1, start, to, mid);
  sb.append(start).append(" ").append(to).append("\n");
  // B-> C
  hanoi(N - 1, mid, start, to);
}
```
