### ISSUE TITLE
[5주차 - 4] 칸토어 집합

### ISSUE THREAD

**Issue by Jewan1120** [T4F1/Algorithm#56]
## 문제 
- 문제 사이트: 백준 
- 문제 이름: [칸토어 집합](https://www.acmicpc.net/problem/4779)
- 문제 번호: 4779

### 문제 풀이 템플릿
```
### 시간복잡도 생각해보기
- 

### 풀이 아이디어
- 

### 의사코드 / 풀이 과정
- 

```

**Comment by yereumi** [comment]
### 시간복잡도 생각해보기
- 신경쓰지 않아도 된다.

### 풀이 아이디어
- depth가 0이면 return한다.
- 가운데 영역을 없애고, 나머지 두 영역에 대해서는 재귀적으로 해결한다.

### 의사코드 / 풀이 과정
```java
if (depth == 0) {
	return;
}
for (int i = start + (int)Math.pow(3, depth - 1); i < start + 2 * (int)Math.pow(3, depth - 1); i++) {
	cantor[i] = false;
}
recursive(depth - 1, start);
recursive(depth - 1, start + (int)Math.pow(3, depth - 1) * 2);
```

**Comment by rladmstn** [comment]
### 시간복잡도 생각해보기
- 0 <= N <= 12
- 상관 없는 듯

### 풀이 아이디어
- arr 값이 true면 " ", false면 "-" 출력
- 탐색할 시작 인덱스, 탐색할 끝 인덱스, 지울 길이를 파라미터로 입력 받음
- 지우고 남은 부분에 대해 재귀적으로 제거
- 탐색의 시작과 끝 인덱스가 같을 때 return

### 의사코드 / 풀이 과정
```java
 private static void cantor(int start, int end, int x) {
        if (start == end) {
            return;
        }

        // 지울 인덱스 범위 계산
        int spaceStart = start + x;
        int spaceEnd = end - x;

        for(int i=spaceStart; i<=spaceEnd; i++){
            arr[i] = true;
        }

        cantor(start,spaceStart-1,x/3);
        cantor(spaceEnd+1, end, x/3);
 }
```

**Comment by yeo-li** [comment]
### 시간복잡도 생각해보기
- 고려 하지 않음.

### 풀이 아이디어
- 크기가 3^N인 boolean 배열을 선언한 뒤, 시작 인덱스, 끝 인덱스를 받는다. 그리고 재귀적으로 l, r 인덱스를 쪼개며 길이(r - l + 1)가 1이 될 때 까지 반복한다.

### 의사코드 / 풀이 과정
```java
void cantorSet(int l, int r) {
	int length = r - l + 1;
	if(length == 1) {
		result[l] = true;
		return;
	}
	cantorSet(l, l + length/3 - 1);
	cantorSet(r - length/3 + 1, r);
}
```

**Comment by Jewan1120** [comment]
### 시간복잡도 생각해보기
- N은 0보다 크거나 같고, 12보다 작거나 같은 정수
- 메모리 초과를 생각하라는 문제 같은데 상관 없는 듯

### 풀이 아이디어
- 3^n의 길이를 3개로 나눠서 풀이 `-` ` ` `-`로 분할 풀이 &rarr; 분할 정복
- 기저 조건은 `depth == 0`일 때 `-`를 출력하고 반환

### 의사코드 / 풀이 과정
```java
static StringBuilder sb = new StringBuilder // 문자열 저장할 객체

// 분할 정복
private static void recursive(int depth) {
    // 종료 조건
    if (depth == 0) {
        sb.append("-");
        return;
    }
    // 3가지로 분할
    recursive(depth - 1);
    sb.append(" ".repeat((int) Math.pow(3, depth - 1))); // 빈 공간
    recursive(depth - 1);
}
```

**Comment by chaerish** [comment]
### 시간복잡도 생각해보기
- 재귀라 고려하지 않았지만 최대 12라 매우 널널할 것 같다
### 풀이 아이디어
- 반복적으로 공백으로 만드는 과정이므로 재귀를 이용한다.
- 직접 잘라보면 depth는 N이다. 따라서 depth가 0일때 멈춘다. 
<img width="494" alt="스크린샷 2024-12-25 04 47 28" src="https://github.com/user-attachments/assets/ab63e886-32ed-4803-abbf-bf188ccc3c06" />

### 의사코드 / 풀이 과정
```java
private static void makeCantor(StringBuilder sb, int start, int end, int depth) {
    if (depth == 0) {
        return;
    }
    int third = (end - start + 1) / 3; //구간 길이 3등분
    int midStart = start + third; // 가운데 구간의 시작 인덱스
    int midEnd = midStart + third - 1; //가운데 구간의 끝 인덱스
    for (int i = midStart; i <= midEnd; i++) {
        sb.setCharAt(i, ' ');
    }
    makeCantor(sb, start, midStart - 1, depth - 1); //왼쪽
    makeCantor(sb, midEnd + 1, end, depth - 1); //오른쪽
}
```
