### ISSUE TITLE
[1주차 - 6] 과일 서리

### ISSUE THREAD

**Issue by Jewan1120** [T4F1/Algorithm#8]
## 문제 
- 문제 사이트: 백준
- 문제 이름: [과일 서리](https://www.acmicpc.net/problem/17213)
- 문제 번호: 17213

### 문제 풀이 템플릿
```
### 시간복잡도 생각해보기
- 

### 풀이 아이디어
- 

### 의사코드
- 

```

**Comment by rladmstn** [comment]
### 시간복잡도 생각해보기
- 1 ≤ N ≤ 10
- N ≤ M ≤ 30
- 조합 dp 값 구하기 : 최대 순회 `O(N^2)`

### 풀이 아이디어
- `nHr = n+r+1Cr`을 사용
- `dp[n][m]` : n개 중 m개 선택하는 조합 경우의 수
- 점화식 : `dp[n][m] = dp[n-1][m-1] + dp[n-1][m]` 
- 이번 문제는 각 종류별로 1개 이상은 무조건 선택해야 하므로, `nH(m-n)`
- 답은 `nH(m-n) = (m-1)C(m-n)`이기에 `dp[m-1][m-n]`를 출력하면 됨

### 의사코드
- 생략

**Comment by yereumi** [comment]
### 시간복잡도 생각해보기
- `O((N+M)*M)`
이차원 배열의 크기만큼 순회하므로 `O(N+M)` * `O(M)` = `O((N+M)*M)`

### 풀이 아이디어
- 파스칼의 삼각형을 이차원 배열(pascal[n][m])로 선언하고, 중복조합을 공식에 맞게 조합으로 바꾼다.
- 이차원 배열을 재귀적으로 순회하며 값을 구한다.
  - pascal[n][r] 0이 아니면 바로 반환
  - 값이 n == r 이거나 r == 0이면 pascal[n][r] = 1
  - 둘 다 아니면 pascal[n][r] = combination(n-1, r-1) + combination(n-1, r) 재귀적으로 계산 후 반환

### 의사코드
- 생략

**Comment by yeo-li** [comment]
### 시간복잡도 생각해보기
- 조건 : N(1 ≤ N ≤ 10), M(N ≤ M ≤ 30)
- `M - 1` 까지의 파스칼의 삼각형 구하기 → `O(M^2)`
- 최종 시간 복잡도  → `O(M^2)`

### 풀이 아이디어
- 중복조합 문제이므로 이항계수로 변환하여 답안 도출하기
- `C(M-1, M-N)`을 도출하면 되는 문제임

### 의사코드
- 생략

**Comment by Jewan1120** [comment]
### 시간복잡도 생각해보기
- 수학 문제라서 딱히 고려하지 않았음

### 풀이 아이디어
- 중복 조합을 이용 &rarr; $`_n\mathbf{H}_r = _{n+r-1}\mathbf{C}_r`$
- 해당 문제는 `단, 모든 종류의 과일을 적어도 1개는 훔친다.`의 조건이 있으므로 $`_n\mathbf{H}_{m-n}`$으로 계산
- 식을 정리한 최종 수식은 $`_{m-1}\mathbf{C}_{m-n}`$ = $` \frac{(m-1)!}{(m-n)!\times(n-1)!}`$으로 정리 후 계산
### 의사코드
- 생략

**Comment by chaerish** [comment]
### 시간복잡도 생각해보기
- N과 M이 숫자가 크지 않아서 재귀로 구현했다. 
- 조합 계산에서 재귀 호출의 구조는 파스칼 삼각형의 노드 수와 동일해서, 시간 복잡도는 `O(2^n)`
### 풀이 아이디어
- C(n,r)=C(n−1,r−1)+C(n−1,r) 
- C(n,0)=1: 아무것도 선택하지 않는 경우는 항상 1가지.
- C(n,n)=1: 모든 것을 선택하는 경우는 항상 1가지.
![image](https://github.com/user-attachments/assets/15a70205-056b-4aca-85b5-c2b2deba2422)
### 의사코드
-
